export const actionTypes = {
    REQUEST_ARTICLE_LIST: 'REQUEST_ARTICLE_LIST',
    RECEIVE_ARTICLE_LIST: 'RECEIVE_ARTICLE_LIST',
    REQUEST_NAVBAR: 'REQUEST_NAVBAR',
    RECEIVE_NAVBAR: 'RECEIVE_NAVBAR'
};